"""User.name nullable

Revision ID: 0f566066952c
Revises: 7ee6c57839aa
Create Date: 2020-09-27 13:18:32.546187

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f566066952c"
down_revision = "7ee6c57839aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=10), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=10), nullable=False)
    # ### end Alembic commands ###
