"""init User model

Revision ID: 7ee6c57839aa
Revises: 963d2bd58576
Create Date: 2020-09-27 12:15:36.017240

"""


# revision identifiers, used by Alembic.
revision = "7ee6c57839aa"
down_revision = "963d2bd58576"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
