name: docs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'docs/**'

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
          node-version: '12.x'

    - name: Install dependencies for docs
      run: yarn install
      working-directory: ./docs

    - name: Build docs site
      run: yarn build
      working-directory: ./docs
    

  gh-release:
      if: github.event_name == 'push'
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses: webfactory/ssh-agent@v0.4.0
          with:
            ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
            ssh-auth-sock: /tmp/ssh_agent.sock
            
        - uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: Release to GitHub Pages
          env:
            USE_SSH: true
            GIT_USER: git
          working-directory: ./docs
          run: |
              git config --global user.email "actions@gihub.com"
              git config --global user.name "gh-actions"
              if [ -e yarn.lock ]; then
              yarn install --frozen-lockfile
              elif [ -e package-lock.json ]; then
              npm ci
              else
              npm i
              fi
              npx docusaurus deploy
