name: Smoke Test for backend

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - "docs/**"
  pull_request:
    branches-ignore:
        - gh-pages
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and start the stack
        run: |
          ./onboarding.sh
          docker-compose up
