name: Build DocsSite

on:
  push:
    branches-ignore:
      - gh-pages
    paths:
      - "docs/**"
      - ".github/workflows/test_build_docs.yml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install and build
        run: |
          yarn install
          yarn build
        working-directory: ./docs
